AllCops:
  NewCops: enable

# This cop makes the hangman ASCII art unintelligible in source, though they print out just fine.
Layout/LineContinuationLeadingSpace:
  Exclude:
    - lib/hangman_stage.rb